output: "{{.Dir}}/README.md"
header: |+
  [![GitHub Actions](https://github.com/logshell/driftctl-slack/actions/workflows/ci.yml/badge.svg?branch=main)](https://github.com/logshell/driftctl-slack/actions/workflows/ci.yml)

  
repository:
  url: https://github.com/logshell/driftctl-slack
  defaultBranch: main
  path: /