output: "{{.Dir}}/README.md"
header: |+
  [![GitHub Actions](https://github.com/nomadops/driftctl-slack/actions/workflows/ci.yml/badge.svg?branch=main)](https://github.com/nomadops/driftctl-slack/actions/workflows/ci.yml)

  driftctl-slack is a golang wrapper to send driftctl scan summary to slack.

  We've provided a [Terraform module](https://github.com/nomadops/terraform-aws-driftctl-slack) for deployment as a scheduleds ECS Fargate task. 

  
repository:
  url: https://github.com/nomadops/driftctl-slack
  defaultBranch: main
  path: /